package exercise4.models.enums;

public enum ConditionIVA {

    IVA_RESPONSABLE_INSCRIPTO, IVA_RESPONSABLE_NO_INSCRIPTO, IVA_NO_RESPONSABLE, IVA_SUJETO_EXENTO, CONSUMIDOR_FINAL,
    RESPONSABLE_MONOTRIBUTO, SUJETO_NO_CATEGORIZADO, PROVEEDOR_DEL_EXTERIOR, CLIENTE_DEL_EXTERIOR, IVA_LIBERADO,
    IVA_RESPONSABLE_INSCRIPTO_AGENTE_DE_PERCEPCION, PEQUENIO_CONTRIBUYENTE_EVENTUAL, MONOTRIBUTISTA_SOCIAL;

}
